import { PullCard } from "../models/CardModel";

export const mockAllCards: PullCard[] = [
    {
        id: 1,
        img: "1_travis_avery",
        name: "Travis Avery",
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 2,
        img: '2_doug_punny',
        name: 'Doug Punny',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 3,
        img: '3_billy_kimber',
        name: "Billy Kimber",
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 4,
        img: '4_gale_summers',
        name: 'Gale Summers',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 5,
        img: '5_micky_burrows',
        name: 'Micky Burrows',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 6,
        img: '6_alex_foley',
        name: 'Alex Foley',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    // {
    //     id: 7,
    //     type: 5,
    //     img: 'full_bakersfield_p',
    //     name: 'Peter Bakersfield',
    //     set: "1A",
    //     specialTag: "",
    // pattern: "",
    // },
    {
        id: 8,
        img: '8_mitar',
        name: 'Mitar',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 26,
        img: '26_25_cent',
        name: '25 Cent',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 28,
        img: '28_john_castle',
        name: 'John Castle',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 31,
        img: '31_charlie_chaplin',
        name: 'Charlie Chaplin',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 35,
        img: '35_bo_bleep',
        name: 'Bo Bleep',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 46,
        img: '46_georgia_pat',
        name: 'Georgia Pat',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 111,
        img: '111_mission_row_pd',
        name: 'Mission Row PD',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 112,
        img: '112_pillbox_medical_center',
        name: 'Pillbox Medical Center',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 113,
        img: '113_little_seoul_gas_station',
        name: 'Little Seoul Gas Station',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 114,
        img: '114_the_bridge',
        name: 'The Bridge',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 115,
        img: '115_pacific_standard',
        name: 'Pacific Standard',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 116,
        img: '116_diamond_casino',
        name: 'Diamond Casino',
        set: "1A",
        specialTag: "",
        pattern: "",
    },
    {
        id: 52,
        img: '52_k_roy',
        name: 'K-Roy',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
    {
        id: 53,
        img: '53_harley_petrov',
        name: 'Harley Petrov',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
    {
        id: 64,
        img: '64_yuki_gasai',
        name: 'Yuki Gasai',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
    {
        id: 90,
        img: '90_avarian_knight',
        name: 'Avarian Knight',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
    {
        id: 93,
        img: '93_bagman',
        name: 'BagMan',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
    {
        id: 100,
        img: '100_putts_bramfield',
        name: 'Putts Bramfield',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
    {
        id: 110,
        img: '110_pookie_snackson_chupador',
        name: 'Pookie Snackson-Chupador',
        set: '1A',
        specialTag: '',
        pattern: '',
    },
]