import { Card } from "../models/CardModel";

export const CardList: Card[] = [
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "gale_s",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 0,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "gale_s",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 0,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "gale_s",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 0,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "gale_s",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 0,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "gale_s",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 0,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "gale_s",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 0,
        uid: "eUtNPc5ra3UszKj",
    },

]