import { CardShorthand } from "../models/CardModel";

export const mockAllCards: CardShorthand[] = [
    {
        id: 1,
        type: 0,
        img: "derek_f",
        name: "Derek Fhreebs",
        set: "1A",
        specialTag: "",
    },
    {
        id: 2,
        type: 0,
        img: 'capt_john_p',
        name: 'Captain John Price',
        set: "1A",
        specialTag: "",
    },
    {
        id: 3,
        type: 0,
        img: 'travis_a',
        name: "Travis Avery",
        set: "1A",
        specialTag: "",
    },
    {
        id: 4,
        type: 0,
        img: 'doug_p',
        name: 'Doug Punny',
        set: "1A",
        specialTag: "",
    },
    {
        id: 5,
        type: 0,
        img: 'billy_k',
        name: 'Billy Kimber',
        set: "1A",
        specialTag: "",
    },
    {
        id: 6,
        type: 0,
        img: 'gale_s',
        name: 'Gale Summers',
        set: "1A",
        specialTag: "",
    },
    {
        id: 7,
        type: 5,
        img: 'full_bakersfield_p',
        name: 'Peter Bakersfield',
        set: "1A",
        specialTag: "",
    },
    {
        id: 8,
        type: 5,
        img: 'full_brees_m',
        name: 'Matt Alucard Brees',
        set: "1A",
        specialTag: "",
    },
    {
        id: 9,
        type: 6,
        img: 'g_demon_t',
        name: 'Demon Time Tony',
        set: "1A",
        specialTag: "",
    },
    {
        id: 10,
        type: 6,
        img: 'g_georgia_p',
        name: 'Demon Time Tony',
        set: "1A",
        specialTag: "",
    },
    {
        id: 11,
        type: 7,
        img: 'b_demon_t',
        name: 'Demon Time Tony',
        set: "1A",
        specialTag: "",
    },
    {
        id: 12,
        type: 7,
        img: 'b_nick_e',
        name: 'Nick Ender',
        set: "1A",
        specialTag: "",
    },
    {
        id: 13,
        type: 8,
        img: 'r_demon_t',
        name: 'Demon Time Tony',
        set: "1A",
        specialTag: "",
    },
    {
        id: 14,
        type: 8,
        img: 'r_putts_b',
        name: 'Putts Bramfield',
        set: "1A",
        specialTag: "",
    },
]