import { Card } from "../models/CardModel";

export const CardList: Card[] = [
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "64_yuki_gasai",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 6,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 1,
        img: "26_25_cent",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 1,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 6,
        img: "26_25_cent",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 2,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 53,
        img: "53_harley_petrov",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 4,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 12,
        img: "90_avarian_knight",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 7,
        uid: "eUtNPc5ra3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "",
        holoY: "",
        id: 21,
        img: "21_vaughn_price",
        like: false,
        name: "Gale Summers",
        pattern: "",
        set: "1A",
        specialTag: "",
        type: 3,
        uid: "eUtNPc5ra3UszKj",
    },

]