export const mockTradeData = {
    localSelected: [
        {
            card_back: "back_1A",
            holoX: "",
            holoY: "",
            id: 1,
            img: "26_25_cent",
            name: "Gale Summers",
            pattern: "",
            set: "1A",
            specialTag: "",
            type: 1,
            uid: "eUtNPc5ra3UszPj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "0%",
            holoY: "0%",
            id: 6,
            img: "26_25_cent",
            name: "Gale Summers",
            pattern: "holo_large",
            set: "1A",
            specialTag: "",
            type: 2,
            uid: "eUtNPc5Aa3UszKj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "",
            holoY: "",
            id: 53,
            img: "53_harley_petrov",
            name: "Gale Summers",
            pattern: "",
            set: "1A",
            specialTag: "",
            type: 4,
            uid: "eUtNPc5ra3UszLj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "",
            holoY: "",
            id: 151,
            img: "151_putts_bramfield",
            name: "Putts Bramfield",
            pattern: "sparkle",
            set: "1A",
            specialTag: "",
            type: 8,
            uid: "WERGWra3UszKj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "99%",
            holoY: "99%",
            id: 21,
            img: "21_vaughn_price",
            name: "Gale Summers",
            pattern: "holo_large",
            set: "1A",
            specialTag: "",
            type: 3,
            uid: "ZZXCAXVAS3UszKj",
            like: false,
            forTrade: true,
        },
    ],
    remoteSelected: [
        {
            card_back: "back_1A",
            holoX: "",
            holoY: "",
            id: 1,
            img: "26_25_cent",
            name: "Gale Summers",
            pattern: "",
            set: "1A",
            specialTag: "",
            type: 1,
            uid: "eUtNPc5ra3UszPj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "0%",
            holoY: "0%",
            id: 6,
            img: "26_25_cent",
            name: "Gale Summers",
            pattern: "holo_large",
            set: "1A",
            specialTag: "",
            type: 2,
            uid: "eUtNPc5Aa3UszKj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "",
            holoY: "",
            id: 53,
            img: "53_harley_petrov",
            name: "Gale Summers",
            pattern: "",
            set: "1A",
            specialTag: "",
            type: 4,
            uid: "eUtNPc5ra3UszLj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "",
            holoY: "",
            id: 151,
            img: "151_putts_bramfield",
            name: "Putts Bramfield",
            pattern: "sparkle",
            set: "1A",
            specialTag: "",
            type: 8,
            uid: "WERGWra3UszKj",
            like: false,
            forTrade: true,
        },
        {
            card_back: "back_1A",
            holoX: "99%",
            holoY: "99%",
            id: 21,
            img: "21_vaughn_price",
            name: "Gale Summers",
            pattern: "holo_large",
            set: "1A",
            specialTag: "",
            type: 3,
            uid: "ZZXCAXVAS3UszKj",
            like: false,
            forTrade: true,
        },
    ]
}