import { CardBundle } from "../models/CardModel";

export const mockInventory: CardBundle[] = [
    {
        uid: { "SH304KLBSvW3TUt": "back_1A" },
        id: 1,
        type: 0,
        count: 0,
        img: "derek_f",
        name: "Derek Fhreebs",
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "SH304KLBSvW3TUB": "back_1A" },
        id: 1,
        type: 2,
        count: 0,
        img: "derek_f",
        name: "Derek Fhreebs",
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "SH305KLBSvW3TUt": "back_1A" },
        id: 2,
        type: 1,
        count: 1,
        img: 'capt_john_p',
        name: 'Captain John Price',
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "SH306KLBSvW3TUt": "back_1A" },
        id: 5,
        type: 2,
        count: 2,
        img: 'travis_a',
        name: "Travis Avery",
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "OAERIGUHOAEI2H5436": "back_1A" },
        count: 1,
        id: 4,
        type: 3,
        img: 'doug_p',
        name: 'Doug Punny',
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "OAERIGUHOAEI2H5136": "back_1A" },
        count: 1,
        id: 70,
        type: 4,
        img: 'full_bakersfield_p',
        name: 'Peter Bakersfield',
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "OAERIGUAOAEI2H5136": "back_1A" },
        count: 1,
        id: 71,
        type: 5,
        img: 'full_brees_m',
        name: 'Matt Alucard Brees',
        set: "1A",
        specialTag: "lightning",
    },
    {
        uid: { "OEERIGUAOAEI2H5136": "back_1A" },
        count: 1,
        id: 80,
        type: 6,
        img: 'g_demon_t',
        name: 'Demon Time Tony',
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "AEERIGUAOAEI2H5136": "back_1A" },
        count: 1,
        id: 90,
        type: 7,
        img: 'b_demon_t',
        name: 'Demon Time Tony',
        set: "1A",
        specialTag: "",
    },
    {
        uid: { "OERRIGUAOAEI2H5136": "back_1A" },
        count: 1,
        id: 100,
        type: 8,
        img: 'r_putts_b',
        name: 'Putts Bramfield',
        set: "1A",
        specialTag: "",
    },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
    // {
    //     uid: "SH306KLBSvW3TUt",
    //     id: 5,
    //     type: 1,
    //     img: "derek_f",
    //     name: "Danny Rodriguez",
    //     set: "1A",
    //     specialTag: "",
    //     tradable: false,
    //     like: false,
    //     // width: "375px", height: "525px", borderRadius: "5% / 3.5%"
    //     width: "187.5px", height: "262.5px", borderRadius: "5% / 3.5%"
    // },
]