import { Card } from "../models/CardModel";

export const CardList: Card[] = [
    // {
    //     card_back: "back_1A",
    //     holoX: "99%",
    //     holoY: "99%",
    //     id: 6,
    //     img: "19_jessica_angelina",
    //     name: "Yuki Gasai",
    //     pattern: "holo_large",
    //     set: "1A",
    //     specialTag: "",
    //     type: 2,
    //     uid: "eUtNPc5raOOOzKj",
    // },
    // {
    //     card_back: "back_1A",
    //     holoX: "",
    //     holoY: "",
    //     id: 1,
    //     img: "26_25_cent",
    //     name: "Gale Summers",
    //     pattern: "",
    //     set: "1A",
    //     specialTag: "",
    //     type: 1,
    //     uid: "eUtNPc5ra3UszPj",
    // },
    // {
    //     card_back: "back_1A",
    //     holoX: "12%",
    //     holoY: "15%",
    //     id: 6,
    //     img: "26_25_cent",
    //     name: "Gale Summers",
    //     pattern: "holo_large",
    //     set: "1A",
    //     specialTag: "",
    //     type: 7,
    //     uid: "eUtNPc5Aa3UszKj",
    // },
    // {
    //     card_back: "back_1A",
    //     holoX: "25%",
    //     holoY: "95%",
    //     id: 97,
    //     img: "97_jackie_wang",
    //     name: "Gale Summers",
    //     pattern: "holo_large",
    //     set: "1A",
    //     specialTag: "",
    //     type: 4,
    //     uid: "eUtNPc5ra3UszLj",
    // },
    // {
    //     card_back: "back_1A",
    //     holoX: "",
    //     holoY: "",
    //     id: 151,
    //     img: "151_putts_bramfield",
    //     name: "Putts Bramfield",
    //     pattern: "sparkle",
    //     set: "1A",
    //     specialTag: "",
    //     type: 8,
    //     uid: "WERGWra3UszKj",
    // },
    {
        card_back: "back_1A",
        holoX: "0%",
        holoY: "0%",
        id: 21,
        img: "21_vaughn_price",
        name: "Gale Summers",
        pattern: "holo_large",
        set: "1A",
        specialTag: "",
        type: 3,
        uid: "ZZqwdszKj",
    },
    {
        card_back: "back_1A",
        holoX: "50%",
        holoY: "50%",
        id: 97,
        img: "97_jackie_wang",
        name: "Jackie Wang",
        pattern: "holo_large",
        set: "1A",
        specialTag: "",
        type: 4,
        uid: "aa",
    },
    {
        card_back: "back_1A",
        holoX: "100%",
        holoY: "100%",
        id: 21,
        img: "21_vaughn_price",
        name: "Gale Summers",
        pattern: "holo_large",
        set: "1A",
        specialTag: "",
        type: 3,
        uid: "ZZXCAXVASUszKj",
    },
    {
        card_back: "back_1A",
        holoX: "100%",
        holoY: "50%",
        id: 21,
        img: "21_vaughn_price",
        name: "Gale Summers",
        pattern: "holo_large",
        set: "1A",
        specialTag: "",
        type: 2,
        uid: "Z1XCAXVAUszKj",
    },
    {
        card_back: "back_1A",
        holoX: "12%",
        holoY: "50%",
        id: 21,
        img: "21_vaughn_price",
        name: "Gale Summers",
        pattern: "holo_large",
        set: "1A",
        specialTag: "",
        type: 2,
        uid: "qwdqwdAS3UszKj",
    },
    {
        card_back: "back_1A",
        holoX: "12%",
        holoY: "12%",
        id: 21,
        img: "21_vaughn_price",
        name: "Gale Summers",
        pattern: "holo_large",
        set: "1A",
        specialTag: "",
        type: 2,
        uid: "qwdqwdqwd",
    },

]