import { CardBundle } from "../models/CardModel";

export const mockInventory: CardBundle[] = [
    // {
    //     uid: {
    //         "SH304KLSSvW3TUt": {
    //             back: "back_1A",
    //             pattern: '',
    //         }
    //     },
    //     id: 90,
    //     count: 1,
    //     type: 7,
    //     img: '90_avarian_knight',
    //     name: 'Avarian Knight',
    //     set: '1A',
    //     specialTag: '',
    // },
    {
        uid: {
            "SH304KLBSvW3TUB": {
                back: "back_1A",
                pattern: 'holo_large',
                holoX: "12%",
                holoY: "77%",
                like: false,
                forTrade: false,
            }
        },
        id: 100,
        count: 1,
        type: 8,
        img: '151_putts_bramfield',
        name: 'Putts Bramfield',
        set: '1A',
        specialTag: '',
    },
    {
        uid: {
            "SH304KLBSvQ3TUB": {
                back: "back_1A",
                pattern: '',
                like: false,
                forTrade: false,
            }
        },
        id: 110,
        count: 1,
        type: 8,
        img: '165_pookie_snaxson',
        name: 'Pookie Snaxson',
        set: '1A',
        specialTag: '',
    },
    {
        uid: {
            "AA305KLBSvW3BUt": {
                back: "back_1A",
                pattern: '',
                holoX: "12%",
                holoY: "77%",
                like: false,
                forTrade: false,
            },
            "WEORIHU432OIHU11": {
                back: "back_1A",
                pattern: '',
                holoX: "5%",
                holoY: "95%",
                like: false,
                forTrade: false,
            }
        },
        type: 5,
        count: 2,
        id: 46,
        img: '46_georgia_pat',
        name: 'Georgia Pat',
        set: '1A',
        specialTag: 'lightning',
    },
    {
        uid: {
            "AC305KLBSvW3BUt": {
                back: "back_1A",
                holoX: "5%",
                holoY: "95%",
                pattern: 'holo_large',
                like: false,
                forTrade: false,
            },
        },
        type: 4,
        count: 1,
        id: 46,
        img: '46_georgia_pat',
        name: 'Georgia Pat',
        set: '1A',
        specialTag: '',
    },
    {
        uid: {
            "SH305KLBSvW3BUt": {
                back: "back_1A",
                pattern: '',
                like: false,
                forTrade: false,
            }
        },
        type: 4,
        count: 2,
        id: 52,
        img: '52_k_roy',
        name: 'K-Roy',
        set: '1A',
        specialTag: '',
    },
    {
        uid: {
            "SH30LBSvW3BUt": {
                back: "back_1A",
                pattern: '',
                like: false,
                forTrade: false,
            }
        },
        type: 4,
        count: 2,
        id: 53,
        img: '53_harley_petrov',
        name: 'Harley Petrov',
        set: '1A',
        specialTag: '',
    },
    {
        uid: {
            "OAERIGUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERIGUOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAEROAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAEEIGUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERIGGHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERIGUHAAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERIG2HOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAERIGUH1AEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "4AERIGUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OAE5IGUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
            "OA6IGUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            },
        },
        id: 1,
        type: 0,
        count: 12,
        img: '1_travis_avery',
        name: "Travis Avery",
        set: "1A",
        specialTag: "",
    },
    {
        uid: {
            "OAERIGUHOAEI2H5436": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            }
        },
        id: 113,
        count: 1,
        type: 0,
        img: '113_little_seoul_gas_station',
        name: 'Little Seoul Gas Station',
        set: "1A",
        specialTag: "",
    },
    {
        uid: {
            "OAERIGUHOAEI2H5336": {
                back: "back_1A",
                pattern: "",
                holoX: "",
                holoY: "",
                like: false,
                forTrade: false,
            }
        },
        id: 113,
        count: 1,
        type: 1,
        img: '113_little_seoul_gas_station',
        name: 'Little Seoul Gas Station',
        set: "1A",
        specialTag: "",
    },
    {
        uid: {
            "ERRIGUHOAEI2H5336": {
                back: "back_1A",
                pattern: "holo_large",
                holoX: "12%",
                holoY: "0%",
                like: false,
                forTrade: false,
            }
        },
        id: 113,
        count: 1,
        type: 3,
        img: '113_little_seoul_gas_station',
        name: 'Little Seoul Gas Station',
        set: "1A",
        specialTag: "",
    },
    {
        uid: {
            "OAERIGUHAAEI2H5436": {
                back: "back_1A",
                pattern: "holo_large",
                holoX: "12%",
                holoY: "56%",
                like: false,
                forTrade: false,
            },
            "BAERIGUHAAEI2H5436": {
                back: "back_1A",
                pattern: "holo_large",
                holoX: "22%",
                holoY: "99%",
                like: false,
                forTrade: false,
            },
            "CAERIGUHAAEI2H5436": {
                back: "back_1A",
                pattern: "holo_large",
                holoX: "78%",
                holoY: "21%",
                like: false,
                forTrade: false,
            }
        },
        id: 113,
        count: 3,
        type: 2,
        img: '113_little_seoul_gas_station',
        name: 'Little Seoul Gas Station',
        set: "1A",
        specialTag: "",
    },
    // {
    //     uid: {
    //         "OAEYIGUHAAEI2H5436": {
    //             back: "back_1A",
    //             pattern: "sparkle",
    //             like: false,
    //             forTrade: false,
    //         }
    //     },
    //     id: 64,
    //     count: 1,
    //     type: 6,
    //     img: '64_yuki_gasai',
    //     name: 'Yuki Gasai',
    //     set: "1A",
    //     specialTag: "",
    // },
    {
        uid: {
            "OAEYIGUHAAEE2H5436": {
                back: "back_1A",
                pattern: "sparkle",
                like: false,
                forTrade: false,
            }
        },
        id: 93,
        count: 1,
        type: 6,
        img: '93_bagman',
        name: 'BagMan',
        set: "1A",
        specialTag: "",
    },

]